version: "3.7"

services:
    database:
        image: postgres
        container_name: database_micron
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=db_micron
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local